/*
 * TODO: define error code in this file
 */
#define TFTP_ERROR_INVALID_ARGUMENT_COUNT 11
#define TFTP_ERROR_INVALID_OPCODE 12
#define TFTP_ERROR_ILLEGAL_OPERATION 13
#define TFTP_ERROR_SEND_FAILED 14
#define TFTP_ERROR_RECEIVE_FAILED 15
#define TFTP_ERROR_FAILED 16
